
 const data = [
  {
    id: 1,
    title: "Cybersecurity Essentials",
    subtitle: "Secure Your Future",
    date: "2025/01/01",
    backgroundColor: "#FFFFFF",
    textColor: "#000000",
    elements: [
      {
        id: "title-box",
        type: "shape",
        shape: "rectangle",
        x: 100,
        y: 60,
        width: 600,
        height: 90,
        borderColor: "#00AEEF",
        borderWidth: 3,
        borderRadius: 2,
      },
      {
        id: "title",
        type: "text",
        content: "Cybersecurity Essentials",
        x: 120,
        y: 80,
        width: 560,
        height: 50,
        fontSize: 40,
        fontWeight: "bold",
        color: "#000000",
        fontFamily: "Arial, Poppins",
        textAlign: "center",
      },
      {
        id: "dots",
        type: "group",
        elements: [
          {
            id: "dot-1",
            type: "shape",
            shape: "circle",
            x: 250,
            y: 40,
            width: 20,
            height: 20,
            borderColor: "#00AEEF",
            borderWidth: 2,
            backgroundColor: "#FFFFFF",
          },
          {
            id: "dot-2",
            type: "shape",
            shape: "circle",
            x: 280,
            y: 40,
            width: 20,
            height: 20,
            backgroundColor: "#00AEEF",
          },
          {
            id: "dot-3",
            type: "shape",
            shape: "circle",
            x: 310,
            y: 40,
            width: 20,
            height: 20,
            borderColor: "#00AEEF",
            borderWidth: 2,
            backgroundColor: "#FFFFFF",
          },
          {
            id: "dot-4",
            type: "shape",
            shape: "circle",
            x: 340,
            y: 40,
            width: 20,
            height: 20,
            backgroundColor: "#00AEEF",
          },
        ],
      },
      {
        id: "illustration",
        type: "image",
        src: "https://cdn-icons-png.flaticon.com/512/2922/2922510.png",
        x: 150,
        y: 180,
        width: 500,
        height: 280,
      },
      {
        id: "author",
        type: "shape",
        shape: "rectangle",
        x: 600,
        y: 480,
        width: 120,
        height: 40,
        backgroundColor: "#00AEEF",
        borderRadius: 20,
      },
      {
        id: "author-text",
        type: "text",
        content: "Kimi AI",
        x: 610,
        y: 490,
        width: 100,
        height: 20,
        fontSize: 16,
        color: "#000000",
        fontFamily: "Arial",
        textAlign: "center",
      },
      {
        id: "date-box",
        type: "shape",
        shape: "rectangle",
        x: 600,
        y: 530,
        width: 120,
        height: 40,
        backgroundColor: "#00AEEF",
        borderRadius: 20,
      },
      {
        id: "date-text",
        type: "text",
        content: "2025/01/01",
        x: 605,
        y: 540,
        width: 110,
        height: 20,
        fontSize: 16,
        color: "#000000",
        fontFamily: "Arial",
        textAlign: "center",
      },
    ],
  },
  {
    id: 2,
    title: "Course Contents",
    backgroundColor: "#10151C",
    textColor: "#FFFFFF",
    elements: [
      {
        id: "contents-title",
        type: "text",
        content: "COURSE MODULES",
        x: 56,
        y: 28,
        width: 688,
        height: 56,
        fontSize: 40,
        fontWeight: "bold",
        color: "#66FCF1",
        fontFamily: "Poppins, Arial",
        textAlign: "center",
        letterSpacing: 0.6,
      },

      {
        id: "card-1",
        type: "shape",
        shape: "rectangle",
        x: 56,
        y: 104,
        width: 328,
        height: 140,
        backgroundColor: "rgba(69,162,158,0.10)",
        borderColor: "#45A29E",
        borderWidth: 1.5,
        borderRadius: 14,
        shadow: true,
      },
      {
        id: "num1",
        type: "text",
        content: "01",
        x: 72,
        y: 116,
        width: 48,
        height: 30,
        fontSize: 24,
        fontWeight: "bold",
        color: "#45A29E",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "topic1",
        type: "text",
        content: "Threat Landscape",
        x: 120,
        y: 116,
        width: 240,
        height: 30,
        fontSize: 20,
        color: "#FFFFFF",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "img1",
        type: "image",
        src: "https://cdn-icons-png.flaticon.com/512/1036/1036237.png",
        x: 72,
        y: 156,
        width: 28,
        height: 28,
      },
      {
        id: "desc1",
        type: "text",
        content: "Common attack types, actors, and trends.",
        x: 108,
        y: 156,
        width: 260,
        height: 72,
        fontSize: 16,
        color: "#D8D8D8",
        fontFamily: "Arial",
        textAlign: "left",
      },

      {
        id: "card-2",
        type: "shape",
        shape: "rectangle",
        x: 416,
        y: 104,
        width: 328,
        height: 140,
        backgroundColor: "rgba(102,252,241,0.08)",
        borderColor: "#66FCF1",
        borderWidth: 1.5,
        borderRadius: 14,
        shadow: true,
      },
      {
        id: "num2",
        type: "text",
        content: "02",
        x: 432,
        y: 116,
        width: 48,
        height: 30,
        fontSize: 24,
        fontWeight: "bold",
        color: "#66FCF1",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "topic2",
        type: "text",
        content: "Network Security",
        x: 480,
        y: 116,
        width: 240,
        height: 30,
        fontSize: 20,
        color: "#FFFFFF",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "img2",
        type: "image",
        src: "https://cdn-icons-png.flaticon.com/512/942/942748.png",
        x: 432,
        y: 156,
        width: 28,
        height: 28,
      },
      {
        id: "desc2",
        type: "text",
        content: "Segmentation, firewalls, IDS/IPS, Zero Trust.",
        x: 468,
        y: 156,
        width: 260,
        height: 72,
        fontSize: 16,
        color: "#D8D8D8",
        fontFamily: "Arial",
        textAlign: "left",
      },

      {
        id: "card-3",
        type: "shape",
        shape: "rectangle",
        x: 56,
        y: 260,
        width: 328,
        height: 140,
        backgroundColor: "rgba(197,198,199,0.08)",
        borderColor: "#C5C6C7",
        borderWidth: 1.5,
        borderRadius: 14,
        shadow: true,
      },
      {
        id: "num3",
        type: "text",
        content: "03",
        x: 72,
        y: 272,
        width: 48,
        height: 30,
        fontSize: 24,
        fontWeight: "bold",
        color: "#C5C6C7",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "topic3",
        type: "text",
        content: "Cloud Security",
        x: 120,
        y: 272,
        width: 240,
        height: 30,
        fontSize: 20,
        color: "#FFFFFF",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "img3",
        type: "image",
        src: "https://cdn-icons-png.flaticon.com/512/633/633682.png",
        x: 72,
        y: 312,
        width: 28,
        height: 28,
      },
      {
        id: "desc3",
        type: "text",
        content: "Shared responsibility, IAM, secrets, posture.",
        x: 108,
        y: 312,
        width: 260,
        height: 72,
        fontSize: 16,
        color: "#D8D8D8",
        fontFamily: "Arial",
        textAlign: "left",
      },

      {
        id: "card-4",
        type: "shape",
        shape: "rectangle",
        x: 416,
        y: 260,
        width: 328,
        height: 140,
        backgroundColor: "rgba(13,110,253,0.10)",
        borderColor: "#0EA5E9",
        borderWidth: 1.5,
        borderRadius: 14,
        shadow: true,
      },
      {
        id: "num4",
        type: "text",
        content: "04",
        x: 432,
        y: 272,
        width: 48,
        height: 30,
        fontSize: 24,
        fontWeight: "bold",
        color: "#0EA5E9",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "topic4",
        type: "text",
        content: "Incident Response",
        x: 480,
        y: 272,
        width: 240,
        height: 30,
        fontSize: 20,
        color: "#FFFFFF",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "img4",
        type: "image",
        src: "https://cdn-icons-png.flaticon.com/512/3075/3075977.png",
        x: 432,
        y: 312,
        width: 28,
        height: 28,
      },
      {
        id: "desc4",
        type: "text",
        content: "Detect, contain, eradicate, recover, learn.",
        x: 468,
        y: 312,
        width: 260,
        height: 72,
        fontSize: 16,
        color: "#D8D8D8",
        fontFamily: "Arial",
        textAlign: "left",
      },
    ],
  },

  {
    id: 3,
    title: "Security Readiness",
    backgroundColor: "#0B0C10",
    textColor: "#FFFFFF",
    elements: [
      {
        id: "main-title",
        type: "text",
        content: "Security Readiness Checklist",
        x: 56,
        y: 28,
        width: 688,
        height: 48,
        fontSize: 32,
        fontWeight: "bold",
        color: "#66FCF1",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "title-underline",
        type: "shape",
        shape: "rectangle",
        x: 56,
        y: 80,
        width: 240,
        height: 6,
        backgroundColor: "#45A29E",
      },

      {
        id: "check-card-1",
        type: "shape",
        shape: "rectangle",
        x: 56,
        y: 104,
        width: 688,
        height: 120,
        backgroundColor: "rgba(69,162,158,0.10)",
        borderColor: "#1F2833",
        borderWidth: 2,
        borderRadius: 16,
        shadow: true,
      },
      {
        id: "check1-icon",
        type: "image",
        src: "https://cdn-icons-png.flaticon.com/512/3064/3064197.png",
        x: 72,
        y: 124,
        width: 40,
        height: 40,
      },
      {
        id: "check1-title",
        type: "text",
        content: "Access Controls",
        x: 128,
        y: 124,
        width: 260,
        height: 34,
        fontSize: 22,
        fontWeight: "bold",
        color: "#45A29E",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "check1-desc",
        type: "text",
        content:
          "RBAC enforced, MFA enabled, least privilege reviewed quarterly.",
        x: 128,
        y: 160,
        width: 596,
        height: 48,
        fontSize: 18,
        color: "#EAEAEA",
        fontFamily: "Arial",
        textAlign: "left",
      },

      {
        id: "check-card-2",
        type: "shape",
        shape: "rectangle",
        x: 56,
        y: 240,
        width: 688,
        height: 120,
        backgroundColor: "rgba(102,252,241,0.08)",
        borderColor: "#1F2833",
        borderWidth: 2,
        borderRadius: 16,
        shadow: true,
      },
      {
        id: "check2-icon",
        type: "image",
        src: "https://cdn-icons-png.flaticon.com/512/3097/3097144.png",
        x: 72,
        y: 260,
        width: 40,
        height: 40,
      },
      {
        id: "check2-title",
        type: "text",
        content: "Patch Management",
        x: 128,
        y: 260,
        width: 280,
        height: 34,
        fontSize: 22,
        fontWeight: "bold",
        color: "#66FCF1",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "check2-desc",
        type: "text",
        content:
          "Critical patches < 7 days; automated updates; vuln scan after patch.",
        x: 128,
        y: 296,
        width: 596,
        height: 48,
        fontSize: 18,
        color: "#EAEAEA",
        fontFamily: "Arial",
        textAlign: "left",
      },

      {
        id: "decor-top",
        type: "shape",
        shape: "circle",
        x: 764,
        y: 28,
        width: 12,
        height: 12,
        backgroundColor: "#66FCF1",
        opacity: 0.9,
      },
    ],
  },

  {
    id: 4,
    title: "Hands-On Labs",
    backgroundColor: "#10151C",
    textColor: "#FFFFFF",
    elements: [
      {
        id: "labs-title",
        type: "text",
        content: "Hands-On Labs",
        x: 56,
        y: 28,
        width: 688,
        height: 48,
        fontSize: 34,
        fontWeight: "bold",
        color: "#66FCF1",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },

      {
        id: "lab-card-a",
        type: "shape",
        shape: "rectangle",
        x: 56,
        y: 92,
        width: 328,
        height: 132,
        backgroundColor: "rgba(14,165,233,0.10)",
        borderColor: "#0EA5E9",
        borderWidth: 1.5,
        borderRadius: 14,
        shadow: true,
      },
      {
        id: "lab-a-title",
        type: "text",
        content: "Wireshark Basics",
        x: 72,
        y: 104,
        width: 296,
        height: 28,
        fontSize: 20,
        fontWeight: "bold",
        color: "#0EA5E9",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "lab-a-desc",
        type: "text",
        content:
          "Capture HTTP traffic, identify suspicious hosts, export evidence.",
        x: 72,
        y: 136,
        width: 296,
        height: 72,
        fontSize: 16,
        color: "#EAEAEA",
        fontFamily: "Arial",
        textAlign: "left",
      },

      {
        id: "lab-card-b",
        type: "shape",
        shape: "rectangle",
        x: 416,
        y: 92,
        width: 328,
        height: 132,
        backgroundColor: "rgba(99,102,241,0.10)",
        borderColor: "#6366F1",
        borderWidth: 1.5,
        borderRadius: 14,
        shadow: true,
      },
      {
        id: "lab-b-title",
        type: "text",
        content: "IAM Hardening",
        x: 432,
        y: 104,
        width: 296,
        height: 28,
        fontSize: 20,
        fontWeight: "bold",
        color: "#6366F1",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "lab-b-desc",
        type: "text",
        content:
          "Rotate keys, enforce MFA, scope least-privilege access for apps.",
        x: 432,
        y: 136,
        width: 296,
        height: 72,
        fontSize: 16,
        color: "#EAEAEA",
        fontFamily: "Arial",
        textAlign: "left",
      },

      {
        id: "lab-card-c",
        type: "shape",
        shape: "rectangle",
        x: 56,
        y: 244,
        width: 328,
        height: 132,
        backgroundColor: "rgba(16,185,129,0.10)",
        borderColor: "#10B981",
        borderWidth: 1.5,
        borderRadius: 14,
        shadow: true,
      },
      {
        id: "lab-c-title",
        type: "text",
        content: "SIEM Triage",
        x: 72,
        y: 256,
        width: 296,
        height: 28,
        fontSize: 20,
        fontWeight: "bold",
        color: "#10B981",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "lab-c-desc",
        type: "text",
        content:
          "Write detection rules, triage alerts, document an incident ticket.",
        x: 72,
        y: 288,
        width: 296,
        height: 72,
        fontSize: 16,
        color: "#EAEAEA",
        fontFamily: "Arial",
        textAlign: "left",
      },

      {
        id: "lab-card-d",
        type: "shape",
        shape: "rectangle",
        x: 416,
        y: 244,
        width: 328,
        height: 132,
        backgroundColor: "rgba(244,63,94,0.10)",
        borderColor: "#F43F5E",
        borderWidth: 1.5,
        borderRadius: 14,
        shadow: true,
      },
      {
        id: "lab-d-title",
        type: "text",
        content: "Phishing Response",
        x: 432,
        y: 256,
        width: 296,
        height: 28,
        fontSize: 20,
        fontWeight: "bold",
        color: "#F43F5E",
        fontFamily: "Poppins, Arial",
        textAlign: "left",
      },
      {
        id: "lab-d-desc",
        type: "text",
        content:
          "Analyze headers, quarantine messages, report indicators of compromise.",
        x: 432,
        y: 288,
        width: 296,
        height: 72,
        fontSize: 16,
        color: "#EAEAEA",
        fontFamily: "Arial",
        textAlign: "left",
      },
    ],
  },

  // {
  //   id: 1,
  //   title: 'Global Makeup Industry Insights',
  //   subtitle: 'Kimi AI',
  //   date: '2025/08/05',
  //   backgroundColor: '#001F54',
  //   textColor: '#ffffff',
  //   elements: [
  //     {
  //       id: 'title',
  //       type: 'text',
  //       content: 'Global Makeup Industry Insights',
  //       x: 80,
  //       y: 80,
  //       width: 600,
  //       height: 70,
  //       fontSize: 48,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'subtitle',
  //       type: 'text',
  //       content: 'Skill Spark',
  //       x: 85,
  //       y: 190,
  //       width: 300,
  //       height: 40,
  //       fontSize: 30,
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'date',
  //       type: 'text',
  //       content: '2025/08/05',
  //       x: 90,
  //       y: 250,
  //       width: 300,
  //       height: 32,
  //       fontSize: 20,
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'circle1',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 0,
  //       y: 0,
  //       width: 40,
  //       height: 40,
  //       backgroundColor: '#ffffff',
  //     },
  //     {
  //       id: 'circle2',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 753,
  //       y: 305,
  //       width: 60,
  //       height: 60,
  //       backgroundColor: '#E63946',
  //     },
  //     // {
  //     //   id: 'dot1',
  //     //   type: 'shape',
  //     //   shape: 'circle',
  //     //   x: 120,
  //     //   y: 40,
  //     //   width: 12,
  //     //   height: 12,
  //     //   backgroundColor: '#ffffff',
  //     // },
  //     // {
  //     //   id: 'dot2',
  //     //   type: 'shape',
  //     //   shape: 'circle',
  //     //   x: 760,
  //     //   y: 60,
  //     //   width: 12,
  //     //   height: 12,
  //     //   backgroundColor: '#E63946',
  //     // },
  //     // {
  //     //   id: 'dot3',
  //     //   type: 'shape',
  //     //   shape: 'circle',
  //     //   x: 760,
  //     //   y: 400,
  //     //   width: 12,
  //     //   height: 12,
  //     //   backgroundColor: '#ffffff',
  //     // }
  //   ],
  // },
  // {
  //   id: 3,
  //   title: 'Contents',
  //   backgroundColor: '#001F54', // navy blue background
  //   textColor: '#ffffff',
  //   elements: [
  //     {
  //       id: 'contents-title',
  //       type: 'text',
  //       content: 'CONTENTS',
  //       x: 53,
  //       y: 30,
  //       width: 600,
  //       height: 80,
  //       fontSize: 72,
  //       fontWeight: '900',
  //       color: '#ffffff', // white title
  //       fontFamily: 'Source Han Sans, Impact, Arial',
  //       textAlign: 'center',
  //     },

  //     // Left column
  //     { id: 'num1', type: 'text', content: '01', x: 98, y: 140, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic1', type: 'text', content: 'Why Go Digital?', x: 183, y: 150, width: 180, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img1', type: 'image', src: 'icons/digital.png', x: 370, y: 145, width: 30, height: 30 },

  //     { id: 'num2', type: 'text', content: '02', x: 98, y: 200, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic2', type: 'text', content: 'Core Features', x: 182, y: 204, width: 180, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img2', type: 'image', src: 'icons/features.png', x: 370, y: 205, width: 30, height: 30 },

  //     { id: 'num3', type: 'text', content: '03', x: 95, y: 259, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic3', type: 'text', content: 'Tech Stack', x: 183, y: 264, width: 180, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img3', type: 'image', src: 'icons/stack.png', x: 370, y: 265, width: 30, height: 30 },

  //     // Right column
  //     { id: 'num4', type: 'text', content: '04', x: 427, y: 143, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic4', type: 'text', content: 'Build & Launch Plan', x: 519, y: 150, width: 220, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img4', type: 'image', src: 'icons/launch.png', x: 740, y: 150, width: 30, height: 30 },

  //     { id: 'num5', type: 'text', content: '05', x: 429, y: 200, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic5', type: 'text', content: 'Success Stories', x: 519, y: 210, width: 220, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img5', type: 'image', src: 'icons/success.png', x: 740, y: 210, width: 30, height: 30 },

  //     { id: 'num6', type: 'text', content: '06', x: 429, y: 260, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic6', type: 'text', content: 'Next Steps', x: 519, y: 270, width: 220, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img6', type: 'image', src: 'icons/next.png', x: 740, y: 270, width: 30, height: 30 },
  //   ],
  // },
  // {
  //   id: 11,
  //   title: 'Kickoff Checklist',
  //   backgroundColor: '#001F54',
  //   textColor: '#ffffff',
  //   elements: [
  //     // Main Title
  //     {
  //       id: 'main-title',
  //       type: 'text',
  //       content: 'Kickoff Checklist',
  //       x: 13,
  //       y: 48,
  //       width: 800,
  //       height: 80,
  //       fontSize: 56,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //     },

  //     // Decorative underline image (red brush underline)
  //     {
  //       id: 'title-underline',
  //       type: 'image',
  //       src: 'https://cdn-icons-png.flaticon.com/512/992/992703.png',
  //       x: 60,
  //       y: 120,
  //       width: 220,
  //       height: 14,
  //     },

  //     // Checklist 1 - with icon
  //     {
  //       id: 'check1-icon',
  //       type: 'image',
  //       src: 'https://cdn-icons-png.flaticon.com/512/1828/1828640.png', // people/stakeholder icon
  //       x: 67,
  //       y: 185,
  //       width: 40,
  //       height: 40,
  //     },
  //     {
  //       id: 'check1-title',
  //       type: 'text',
  //       content: 'Stakeholder Buy-In',
  //       x: 12,
  //       y: 151,
  //       width: 400,
  //       height: 40,
  //       fontSize: 32,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'check1-desc',
  //       type: 'text',
  //       content: 'Secure buy-in from all stakeholders to ensure smooth project execution and alignment with business goals.',
  //       x: 20,
  //       y: 230,
  //       width: 350,
  //       height: 132,
  //       fontSize: 22,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //     },

  //     // Checklist 2 - with icon
  //     {
  //       id: 'check2-icon',
  //       type: 'image',
  //       src: 'https://cdn-icons-png.flaticon.com/512/1828/1828859.png', // checklist/features icon
  //       x: 67,
  //       y: 325,
  //       width: 40,
  //       height: 40,
  //     },
  //     {
  //       id: 'check2-title',
  //       type: 'text',
  //       content: 'Finalize Feature List',
  //       x: 383,
  //       y: 149,
  //       width: 400,
  //       height: 40,
  //       fontSize: 32,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'check2-desc',
  //       type: 'text',
  //       content: 'Finalize the feature list based on stakeholder requirements and market needs to deliver a robust solution.',
  //       x: 394,
  //       y: 259,
  //       width: 329,
  //       height: 100,
  //       fontSize: 22,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //     },

  //     // Decorative corner image
  //     {
  //       id: 'decor-top',
  //       type: 'image',
  //       src: 'https://cdn-icons-png.flaticon.com/512/1828/1828970.png', // dots/pattern
  //       x: 780,
  //       y: 60,
  //       width: 50,
  //       height: 50,
  //     }
  //   ],
  // },

  // {
  //   id: 10,
  //   title: 'Team & Budget Snapshot',
  //   backgroundColor: '#001F54',
  //   textColor: '#ffffff',
  //   elements: [
  //     // Quotation Mark
  //     {
  //       id: 'quote',
  //       type: 'text',
  //       content: '“ ...',
  //       x: 45,
  //       y: 12,
  //       width: 200,
  //       height: 60,
  //       fontSize: 48,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },

  //     // Main Title
  //     {
  //       id: 'main-title',
  //       type: 'text',
  //       content: 'Team & Budget Snapshot',
  //       x: 46,
  //       y: 89,
  //       width: 900,
  //       height: 80,
  //       fontSize: 56,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //     },

  //     // Skilled Team Box
  //     {
  //       id: 'skilled-team-box',
  //       type: 'shape',
  //       shape: 'square',
  //       x: 50,
  //       y: 198,
  //       width: 700,
  //       height: 100,
  //       backgroundColor: 'rgba(255,255,255,0.1)',
  //       borderColor: '#ffffff',
  //       borderWidth: 2,
  //       borderRadius: 12,
  //     },
  //     {
  //       id: 'skilled-team-title',
  //       type: 'text',
  //       content: 'Skilled Team',
  //       x: 56,
  //       y: 203,
  //       width: 400,
  //       height: 40,
  //       fontSize: 32,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'skilled-team-desc',
  //       type: 'text',
  //       content: 'The project requires a skilled team including full-stack developers, a UI designer, QA, and DevOps to ensure success.',
  //       x: 55,
  //       y: 246,
  //       width: 700,
  //       height: 40,
  //       fontSize: 22,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //     },

  //     // Cost-Efficient Budget Box
  //     {
  //       id: 'budget-box',
  //       type: 'shape',
  //       shape: 'square',
  //       x: 51,
  //       y: 329,
  //       width: 700,
  //       height: 100,
  //       backgroundColor: 'rgba(255,255,255,0.1)',
  //       borderColor: '#ffffff',
  //       borderWidth: 2,
  //       borderRadius: 12,
  //     },
  //     {
  //       id: 'budget-title',
  //       type: 'text',
  //       content: 'Cost-Efficient Budget',
  //       x: 63,
  //       y: 334,
  //       width: 400,
  //       height: 40,
  //       fontSize: 32,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'budget-desc',
  //       type: 'text',
  //       content: 'With an initial investment of $25k, the project aims to achieve ROI within eight months through cost savings and increased efficiency.',
  //       x: 67,
  //       y: 376,
  //       width: 700,
  //       height: 40,
  //       fontSize: 22,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //     },

  //     // Decorative dots
  //     {
  //       id: 'dot1',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 800,
  //       y: 60,
  //       width: 14,
  //       height: 14,
  //       backgroundColor: '#ffffff',
  //     },
  //     {
  //       id: 'dot2',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 830,
  //       y: 95,
  //       width: 10,
  //       height: 10,
  //       backgroundColor: '#E63946',
  //     }
  //   ],
  // },
  // {
  //   id: 9,
  //   title: 'Customer Self-Service Portal',
  //   backgroundColor: '#001F54', // Navy Blue Background
  //   textColor: '#ffffff',
  //   elements: [
  //     // Main Title
  //     {
  //       id: 'main-title',
  //       type: 'text',
  //       content: 'Customer Self-Service Portal',
  //       x: 50,
  //       y: 60,
  //       width: 720,
  //       height: 90,
  //       fontSize: 52,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'left',
  //     },

  //     // Red underline bar under title
  //     {
  //       id: 'title-bar',
  //       type: 'shape',
  //       shape: 'rectangle',
  //       x: 50,
  //       y: 135,
  //       width: 350,
  //       height: 6,
  //       backgroundColor: '#E63946',
  //     },

  //     // User-Friendly Interface Box
  //     {
  //       id: 'ufi-box',
  //       type: 'shape',
  //       shape: 'rectangle',
  //       x: 40,
  //       y: 180,
  //       width: 760,
  //       height: 120,
  //       backgroundColor: '#ffffff',
  //       borderColor: '#E63946',
  //       borderWidth: 3,
  //       borderRadius: 16,
  //       shadow: true,
  //     },
  //     {
  //       id: 'ufi-title',
  //       type: 'text',
  //       content: 'User-Friendly Interface',
  //       x: 60,
  //       y: 190,
  //       width: 400,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#001F54',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'ufi-desc',
  //       type: 'text',
  //       content: 'The portal offers a user-friendly interface for customers to register, book refills, and view their subsidy status easily.',
  //       x: 60,
  //       y: 230,
  //       width: 700,
  //       height: 60,
  //       fontSize: 20,
  //       color: '#333333',
  //       fontFamily: 'Arial',
  //     },

  //     // Comprehensive Features Box
  //     {
  //       id: 'cf-box',
  //       type: 'shape',
  //       shape: 'rectangle',
  //       x: 40,
  //       y: 330,
  //       width: 760,
  //       height: 120,
  //       backgroundColor: '#ffffff',
  //       borderColor: '#001F54',
  //       borderWidth: 3,
  //       borderRadius: 16,
  //       shadow: true,
  //     },
  //     {
  //       id: 'cf-title',
  //       type: 'text',
  //       content: 'Comprehensive Features',
  //       x: 60,
  //       y: 340,
  //       width: 400,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'cf-desc',
  //       type: 'text',
  //       content: 'Customers can choose delivery slots, pay online, download invoices, and track their order history, all within the portal.',
  //       x: 60,
  //       y: 380,
  //       width: 700,
  //       height: 60,
  //       fontSize: 20,
  //       color: '#333333',
  //       fontFamily: 'Arial',
  //     },

  //     // Decorative red & white circles
  //     {
  //       id: 'circle-deco1',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 820,
  //       y: 70,
  //       width: 18,
  //       height: 18,
  //       backgroundColor: '#ffffff',
  //     },
  //     {
  //       id: 'circle-deco2',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 850,
  //       y: 100,
  //       width: 14,
  //       height: 14,
  //       backgroundColor: '#E63946',
  //     },
  //     {
  //       id: 'circle-deco3',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 820,
  //       y: 420,
  //       width: 12,
  //       height: 12,
  //       backgroundColor: '#ffffff',
  //     }
  //   ],
  // },
  // {
  //   id: 8,
  //   title: 'Nepal Gas Case Study',
  //   backgroundColor: '#001F54', // Navy Blue background
  //   textColor: '#ffffff',
  //   elements: [
  //     // Main Title
  //     {
  //       id: 'main-title',
  //       type: 'text',
  //       content: 'Nepal Gas Case Study',
  //       x: 45,
  //       y: 33,
  //       width: 800,
  //       height: 80,
  //       fontSize: 54,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //     },

  //     // Row 1
  //     {
  //       id: 'row1-bg',
  //       type: 'shape',
  //       shape: 'square',
  //       x: 40,
  //       y: 140,
  //       width: 716,
  //       height: 80,
  //       backgroundColor: '#ffffff',
  //       borderRadius: 40,
  //     },
  //     {
  //       id: 'row1-num',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 60,
  //       y: 150,
  //       width: 60,
  //       height: 60,
  //       backgroundColor: '#E63946',
  //     },
  //     {
  //       id: 'row1-num-text',
  //       type: 'text',
  //       content: '01',
  //       x: 75,
  //       y: 165,
  //       width: 40,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'row1-title',
  //       type: 'text',
  //       content: 'Significant Improvements',
  //       x: 128,
  //       y: 140,
  //       width: 340,
  //       height: 40,
  //       fontSize: 24,
  //       fontWeight: 'bold',
  //       color: '#001F54',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'row1-desc',
  //       type: 'text',
  //       content: 'Nepal Gas saw booking time reduced from 10 minutes to 30 seconds, increasing online payments to 70% and reducing complaints by 45%.',
  //       x: 131,
  //       y: 172,
  //       width: 588,
  //       height: 40,
  //       fontSize: 16,
  //       color: '#001F54',
  //       fontFamily: 'Arial',
  //     },

  //     // Row 2
  //     {
  //       id: 'row2-bg',
  //       type: 'shape',
  //       shape: 'square',
  //       x: 40,
  //       y: 250,
  //       width: 716,
  //       height: 80,
  //       backgroundColor: '#ffffff',
  //       borderRadius: 40,
  //     },
  //     {
  //       id: 'row2-num',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 60,
  //       y: 260,
  //       width: 60,
  //       height: 60,
  //       backgroundColor: '#E63946',
  //     },
  //     {
  //       id: 'row2-num-text',
  //       type: 'text',
  //       content: '02',
  //       x: 75,
  //       y: 275,
  //       width: 40,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'row2-title',
  //       type: 'text',
  //       content: 'Accurate Demand Forecasting',
  //       x: 137,
  //       y: 250,
  //       width: 367,
  //       height: 40,
  //       fontSize: 24,
  //       fontWeight: 'bold',
  //       color: '#001F54',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'row2-desc',
  //       type: 'text',
  //       content: 'The web app enabled accurate demand forecasting, helping the agency manage inventory effectively during festivals.',
  //       x: 138,
  //       y: 288,
  //       width: 636,
  //       height: 40,
  //       fontSize: 16,
  //       color: '#001F54',
  //       fontFamily: 'Arial',
  //     },

  //     // Row 3
  //     {
  //       id: 'row3-bg',
  //       type: 'shape',
  //       shape: 'square',
  //       x: 40,
  //       y: 360,
  //       width: 716,
  //       height: 80,
  //       backgroundColor: '#ffffff',
  //       borderRadius: 40,
  //     },
  //     {
  //       id: 'row3-num',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 60,
  //       y: 370,
  //       width: 60,
  //       height: 60,
  //       backgroundColor: '#E63946',
  //     },
  //     {
  //       id: 'row3-num-text',
  //       type: 'text',
  //       content: '03',
  //       x: 75,
  //       y: 385,
  //       width: 40,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'row3-title',
  //       type: 'text',
  //       content: 'Customer Satisfaction',
  //       x: 136,
  //       y: 364,
  //       width: 340,
  //       height: 40,
  //       fontSize: 24,
  //       fontWeight: 'bold',
  //       color: '#001F54',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'row3-desc',
  //       type: 'text',
  //       content: 'Improved transparency and real-time tracking significantly enhanced customer satisfaction and loyalty.',
  //       x: 135,
  //       y: 397,
  //       width: 634,
  //       height: 40,
  //       fontSize: 16,
  //       color: '#001F54',
  //       fontFamily: 'Arial',
  //     },
  //   ],
  // },
  // {
  //   id: 7,
  //   title: 'Digital Shift Benefits',
  //   backgroundColor: '#001F54', // Navy blue background
  //   textColor: '#ffffff',
  //   elements: [
  //     // Main Title
  //     {
  //       id: 'main-title',
  //       type: 'text',
  //       content: 'Digital Shift Benefits',
  //       x: 26,
  //       y: 20,
  //       width: 800,
  //       height: 80,
  //       fontSize: 56,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //     },

  //     // Card 1
  //     {
  //       id: 'card1-bg',
  //       type: 'shape',
  //       shape: 'square',
  //       x: 60,
  //       y: 140,
  //       width: 200,
  //       height: 300,
  //       backgroundColor: '#ffffff',
  //     },
  //     {
  //       id: 'card1-num',
  //       type: 'text',
  //       content: '01',
  //       x: 126,
  //       y: 144,
  //       width: 80,
  //       height: 50,
  //       fontSize: 48,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'card1-title',
  //       type: 'text',
  //       content: 'Self-Service Booking',
  //       x: 35,
  //       y: 203,
  //       width: 240,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#001F54',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'card1-desc',
  //       type: 'text',
  //       content: 'A web application allows customers to book refills 24/7, reducing the workload on call centers and improving customer convenience.',
  //       x: 73,
  //       y: 289,
  //       width: 169,
  //       height: 103,
  //       fontSize: 18,
  //       color: '#001F54',
  //       fontFamily: 'Arial',
  //       textAlign: 'left',
  //     },

  //     // Card 2
  //     {
  //       id: 'card2-bg',
  //       type: 'shape',
  //       shape: 'square',
  //       x: 306,
  //       y: 138,
  //       width: 200,
  //       height: 300,
  //       backgroundColor: '#ffffff',
  //     },
  //     {
  //       id: 'card2-num',
  //       type: 'text',
  //       content: '02',
  //       x: 378,
  //       y: 143,
  //       width: 80,
  //       height: 50,
  //       fontSize: 48,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'card2-title',
  //       type: 'text',
  //       content: 'Real-Time Tracking',
  //       x: 281,
  //       y: 206,
  //       width: 240,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#001F54',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'card2-desc',
  //       type: 'text',
  //       content: 'Real-time cylinder tracking ensures transparency and timely delivery, enhancing customer trust and satisfaction.',
  //       x: 333,
  //       y: 273,
  //       width: 146,
  //       height: 127,
  //       fontSize: 18,
  //       color: '#001F54',
  //       fontFamily: 'Arial',
  //       textAlign: 'left',
  //     },

  //     // Card 3
  //     {
  //       id: 'card3-bg',
  //       type: 'shape',
  //       shape: 'square',
  //       x: 553,
  //       y: 134,
  //       width: 200,
  //       height: 300,
  //       backgroundColor: '#ffffff',
  //     },
  //     {
  //       id: 'card3-num',
  //       type: 'text',
  //       content: '03',
  //       x: 620,
  //       y: 141,
  //       width: 80,
  //       height: 50,
  //       fontSize: 48,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'card3-title',
  //       type: 'text',
  //       content: 'Cost Reduction',
  //       x: 551,
  //       y: 200,
  //       width: 193,
  //       height: 42,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#001F54',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'card3-desc',
  //       type: 'text',
  //       content: 'Automated processes and digital payments reduce operational costs by up to 30%, making the business more efficient.',
  //       x: 580,
  //       y: 276,
  //       width: 168,
  //       height: 120,
  //       fontSize: 18,
  //       color: '#001F54',
  //       fontFamily: 'Arial',
  //       textAlign: 'left',
  //     },
  //   ],
  // },
  // {
  //   id: 4,
  //   title: 'Pain Points of Manual Booking',
  //   backgroundColor: '#001F54', // navy blue background
  //   textColor: '#ffffff',
  //   elements: [
  //     {
  //       id: 'main-title',
  //       type: 'text',
  //       content: 'Pain Points of Manual Booking',
  //       x: 48,
  //       y: 40,
  //       width: 800,
  //       height: 60,
  //       fontSize: 44,
  //       fontWeight: 'bold',
  //       color: '#ffffff', // white title
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'left-desc',
  //       type: 'text',
  //       content: 'Manual booking systems often result in missed orders due to human error, leading to lost revenue and dissatisfied customers.',
  //       x: 48,
  //       y: 124,
  //       width: 340,
  //       height: 60,
  //       fontSize: 18,
  //       color: '#ffffff', // white text
  //       fontFamily: 'Arial',
  //       textAlign: 'left',
  //     },
  //     {
  //       id: 'missed-orders-label',
  //       type: 'text',
  //       content: 'Missed Orders',
  //       x: 54,
  //       y: 216,
  //       width: 220,
  //       height: 40,
  //       fontSize: 24,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       backgroundColor: '#E63946', // red label
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'missed-orders-num',
  //       type: 'text',
  //       content: '01',
  //       x: 278,
  //       y: 215,
  //       width: 60,
  //       height: 40,
  //       fontSize: 32,
  //       fontWeight: 'bold',
  //       color: '#E63946', // red number
  //       backgroundColor: '#ffffff', // white background
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //       borderRadius: 20,
  //     },
  //     {
  //       id: 'double-bookings-label',
  //       type: 'text',
  //       content: 'Double Bookings',
  //       x: 53,
  //       y: 261,
  //       width: 220,
  //       height: 40,
  //       fontSize: 24,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       backgroundColor: '#E63946', // red label
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'double-bookings-num',
  //       type: 'text',
  //       content: '02',
  //       x: 276,
  //       y: 261,
  //       width: 60,
  //       height: 40,
  //       fontSize: 32,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       backgroundColor: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //       borderRadius: 20,
  //     },
  //     {
  //       id: 'double-bookings-desc',
  //       type: 'text',
  //       content: 'Double bookings are common with manual ledgers, causing confusion and delays in delivery schedules.',
  //       x: 41,
  //       y: 314,
  //       width: 340,
  //       height: 60,
  //       fontSize: 18,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //       textAlign: 'left',
  //     },
  //     {
  //       id: 'right-desc',
  //       type: 'text',
  //       content: 'Lack of real-time tracking makes it difficult to monitor delivery status, leading to poor customer satisfaction.',
  //       x: 421,
  //       y: 113,
  //       width: 340,
  //       height: 60,
  //       fontSize: 18,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //       textAlign: 'left',
  //     },
  //     {
  //       id: 'delayed-tracking-label',
  //       type: 'text',
  //       content: 'Delayed Tracking',
  //       x: 428,
  //       y: 214,
  //       width: 220,
  //       height: 40,
  //       fontSize: 24,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       backgroundColor: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'delayed-tracking-num',
  //       type: 'text',
  //       content: '03',
  //       x: 370,
  //       y: 215,
  //       width: 60,
  //       height: 40,
  //       fontSize: 32,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       backgroundColor: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //       borderRadius: 20,
  //     },
  //     {
  //       id: 'bottlenecks-label',
  //       type: 'text',
  //       content: 'Operational Bottlenecks',
  //       x: 428,
  //       y: 261,
  //       width: 300,
  //       height: 40,
  //       fontSize: 24,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       backgroundColor: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //     },
  //     {
  //       id: 'bottlenecks-num',
  //       type: 'text',
  //       content: '04',
  //       x: 370,
  //       y: 261,
  //       width: 60,
  //       height: 40,
  //       fontSize: 32,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       backgroundColor: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //       textAlign: 'center',
  //       borderRadius: 20,
  //     },
  //     {
  //       id: 'bottlenecks-desc',
  //       type: 'text',
  //       content: 'Manual processes slow down operations, increasing costs and reducing efficiency in daily activities.',
  //       x: 417,
  //       y: 313,
  //       width: 340,
  //       height: 60,
  //       fontSize: 18,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //       textAlign: 'left',
  //     },
  //   ],
  // },
  // {
  //   id: 6,
  //   title: 'Admin Dashboard & CRM',
  //   backgroundColor: 'linear-gradient(135deg, #001F54 0%, #142850 100%)', // deep navy gradient
  //   textColor: '#fff',
  //   elements: [
  //     // Main Title
  //     {
  //       id: 'main-title',
  //       type: 'text',
  //       content: 'Admin Dashboard & CRM',
  //       x: 50,
  //       y: 40,
  //       width: 700,
  //       height: 80,
  //       fontSize: 56,
  //       fontWeight: 'bold',
  //       color: '#ffffff',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     // Left Column
  //     {
  //       id: 'op-title',
  //       type: 'text',
  //       content: 'Operational Monitoring',
  //       x: 30,
  //       y: 140,
  //       width: 340,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#E63946', // bold red highlight
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'op-desc',
  //       type: 'text',
  //       content: 'Admins can monitor daily bookings, assign deliveries, and track driver routes efficiently.',
  //       x: 30,
  //       y: 180,
  //       width: 340,
  //       height: 60,
  //       fontSize: 18,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //     },
  //     {
  //       id: 'inv-title',
  //       type: 'text',
  //       content: 'Inventory Management',
  //       x: 30,
  //       y: 260,
  //       width: 340,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'inv-desc',
  //       type: 'text',
  //       content: 'The dashboard provides real-time inventory updates, helping admins manage stock levels and avoid shortages.',
  //       x: 30,
  //       y: 300,
  //       width: 340,
  //       height: 60,
  //       fontSize: 18,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //     },
  //     // Divider
  //     {
  //       id: 'divider',
  //       type: 'shape',
  //       shape: 'square',
  //       x: 400,
  //       y: 120,
  //       width: 6,
  //       height: 260,
  //       color: '#ffffff',
  //       backgroundColor: 'rgba(255,255,255,0.25)',
  //     },
  //     // Right Column
  //     {
  //       id: 'crm-title',
  //       type: 'text',
  //       content: 'Customer Relationship Management',
  //       x: 430,
  //       y: 140,
  //       width: 340,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'crm-desc',
  //       type: 'text',
  //       content: 'Built-in CRM tools help identify high-value customers and manage overdue payments, enhancing customer retention.',
  //       x: 430,
  //       y: 200,
  //       width: 340,
  //       height: 60,
  //       fontSize: 18,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //     },
  //     {
  //       id: 'pro-title',
  //       type: 'text',
  //       content: 'Proactive Outreach',
  //       x: 430,
  //       y: 260,
  //       width: 340,
  //       height: 40,
  //       fontSize: 28,
  //       fontWeight: 'bold',
  //       color: '#E63946',
  //       fontFamily: 'Poppins, Arial',
  //     },
  //     {
  //       id: 'pro-desc',
  //       type: 'text',
  //       content: 'CRM enables proactive customer outreach and upselling of accessories, improving overall customer satisfaction.',
  //       x: 430,
  //       y: 300,
  //       width: 340,
  //       height: 60,
  //       fontSize: 18,
  //       color: '#ffffff',
  //       fontFamily: 'Arial',
  //     },
  //     // Decorative Shapes
  //     {
  //       id: 'circle-left',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 60,
  //       y: 380,
  //       width: 40,
  //       height: 40,
  //       color: '#E63946',
  //       backgroundColor: '#E63946',
  //     },
  //     {
  //       id: 'circle-right',
  //       type: 'shape',
  //       shape: 'circle',
  //       x: 700,
  //       y: 40,
  //       width: 25,
  //       height: 25,
  //       color: '#ffffff',
  //       backgroundColor: '#ffffff',
  //     },
  //   ],
  // },
  // {
  //   id: 3,
  //   title: 'Contents',
  //   backgroundColor: '#001F54', // navy blue background
  //   textColor: '#ffffff',
  //   elements: [
  //     {
  //       id: 'contents-title',
  //       type: 'text',
  //       content: 'CONTENTS',
  //       x: 53,
  //       y: 30,
  //       width: 600,
  //       height: 80,
  //       fontSize: 72,
  //       fontWeight: '900',
  //       color: '#ffffff', // white title
  //       fontFamily: 'Source Han Sans, Impact, Arial',
  //       textAlign: 'center',
  //     },

  //     // Left column
  //     { id: 'num1', type: 'text', content: '01', x: 98, y: 140, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic1', type: 'text', content: 'Why Go Digital?', x: 183, y: 150, width: 180, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img1', type: 'image', src: 'icons/digital.png', x: 370, y: 145, width: 30, height: 30 },

  //     { id: 'num2', type: 'text', content: '02', x: 98, y: 200, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic2', type: 'text', content: 'Core Features', x: 182, y: 204, width: 180, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img2', type: 'image', src: 'icons/features.png', x: 370, y: 205, width: 30, height: 30 },

  //     { id: 'num3', type: 'text', content: '03', x: 95, y: 259, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic3', type: 'text', content: 'Tech Stack', x: 183, y: 264, width: 180, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img3', type: 'image', src: 'icons/stack.png', x: 370, y: 265, width: 30, height: 30 },

  //     // Right column
  //     { id: 'num4', type: 'text', content: '04', x: 427, y: 143, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic4', type: 'text', content: 'Build & Launch Plan', x: 519, y: 150, width: 220, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img4', type: 'image', src: 'icons/launch.png', x: 740, y: 150, width: 30, height: 30 },

  //     { id: 'num5', type: 'text', content: '05', x: 429, y: 200, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic5', type: 'text', content: 'Success Stories', x: 519, y: 210, width: 220, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img5', type: 'image', src: 'icons/success.png', x: 740, y: 210, width: 30, height: 30 },

  //     { id: 'num6', type: 'text', content: '06', x: 429, y: 260, width: 80, height: 50, fontSize: 48, fontWeight: 'bold', color: '#E63946', fontFamily: 'Source Han Sans, Arial', textAlign: 'right' },
  //     { id: 'topic6', type: 'text', content: 'Next Steps', x: 519, y: 270, width: 220, height: 40, fontSize: 22, color: '#ffffff', fontFamily: 'Arial', textAlign: 'left' },
  //     { id: 'img6', type: 'image', src: 'icons/next.png', x: 740, y: 270, width: 30, height: 30 },
  //   ],
  // }
];
export default data;